# 1. Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kvontrack-gemini
spec:
  replicas: 1  # SQLite ke liye abhi 1 hi rakho taaki data mismatch na ho
  selector:
    matchLabels:
      app: kvontrack-gemini
  template:
    metadata:
      labels:
        app: kvontrack-gemini
    spec:
      containers:
      - name: kvontrack-gemini
        image: techfaiyaz5/kvontrack-gemini:358
        ports:
        - containerPort: 5000
        env:
        - name: TZ
          value: "Asia/Kolkata"
        securityContext:
          runAsUser: 0  # Isse SQLite file banane ki permission mil jayegi
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
---
# 2. Service (NodePort)
apiVersion: v1
kind: Service
metadata:
  name: kvontrack-gemini-service
spec:
  type: NodePort
  selector:
    app: kvontrack-gemini
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007
---
# 3. HPA (Horizontal Pod Autoscaler)
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kvontrack-gemini-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kvontrack-gemini
  minReplicas: 1 # Jab tak MySQL nahi hai, ise 1 hi rehne do
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50